config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about', as: :about
  get '/work_history', to: 'static_pages#work_history', as: :work_history
  get '/education', to: 'static_pages#education', as: :education

  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/work_history'
  get 'static_pages/education'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	
  end

  def about
  
  end

  def work_history
  
  end

  def education
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav_bar.html.erb
<strong><%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Education', education_path %>
<%= link_to 'Work History', work_history_path %></strong>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vanessa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/nav_bar' %>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/education.html.erb
<h1>StaticPages#education</h1>
<p>Find me in app/views/static_pages/education.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Vanessa Baker</h1>

app/views/static_pages/work_history.html.erb
<h1>StaticPages#work_history</h1>
<p>Find me in app/views/static_pages/work_history.html.erb</p>